# Generated by Django 2.1.5 on 2019-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='image',
            name='summary',
            field=models.CharField(blank=True, help_text='Short description of the image', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='path',
            field=models.CharField(blank=True, help_text='Relative path name of the file', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
